---

go:
  - 1.10
python:
  - 2.7

services: docker

env:
  - distro: ubuntu1204
  - distro: ubuntu1210
  - distro: ubuntu1304
  - distro: ubuntu1310
  - distro: ubuntu1404
  - distro: ubuntu1410
  - distro: ubuntu1504
  - distro: ubuntu1510
  - distro: ubuntu1604
  - distro: ubuntu1610
  - distro: ubuntu1704
  - distro: ubuntu1710
  - distro: ubuntu1804
  - distro: ubuntu1810
  - distro: centos6
  - distro: centos7
  - distro: debian7
  - distro: debian8
  - distro: debian9
  - distro: debian10
  - distro: fedora24
  - distro: fedora25
  - distro: fedora26
  - distro: fedora27
  - distro: fedora28

before_install:
  - go get -v github.com/fubarhouse/ansible-role-tester

script:
  - container_id=$(date +%s)
  - directory=${HOME}/my_role
  - git clone https://github.com/fubarhouse/ansible-role-golang.git ${directory}
  - cd ${directory} && ansible-role-tester run --name ${container_id} --user fubarhouse --distribution ${distro} --source ${HOME}/my_role
  - cd ${directory} && ansible-role-tester install --name ${container_id}
  - travis_wait 30 cd ${directory} && ansible-role-tester test --name ${container_id} --playbook test.yml
  - cd ${directory} && ansible-role-tester destroy --name ${container_id}

